Closes #21 - Enable / Disable CDN with the specified host and zone.
GeekPress/wp-rocket-cli pull request #39
Opened 2020-12-02 20:11 UTC by crystinutzaa

Closes https://github.com/wp-media/wp-rocket-cli/issues/21

Enables / Disables CDN option with host and zone. It merges if the cname exists so it will change the zone.

My question is if we shall clean Rocket cache and minified files after this operation directly from CLI cdn command.
@wp-media/php

2020-12-02 20:45 UTC, Tabrisrp requested changes

2020-12-02 20:45 UTC, Tabrisrp commented on command.php
> +			WP_CLI::error( 'You did\'t specify the "enable" argument.' );
```suggestion
			WP_CLI::error( 'The "enable" argument must be specified.' );
```

2020-12-02 20:47 UTC, Tabrisrp commented
I think it would make sense to do the clean, as it can be easy to forget when changing just this value, and it can create errors if not done.

2020-12-02 21:08 UTC, Tabrisrp approved these changes

2021-01-04 12:43 UTC, crystinutzaa commented
@wp-media/qa  this one is ready for QA

2021-01-11 16:12 UTC, piotrbak commented
@Tabrisrp @crystinutzaa It's expected to remove the zones in the `epic` here:
https://github.com/wp-media/wp-rocket/issues/3417

Should we take it into consideration with this update and allow only for the `all` here?

2021-01-12 22:03 UTC, Tabrisrp commented
The zone value itself won't exist anymore, but we don't know when this will be implemented, so we can go ahead with this for now. We will update it later at the same time we work on the epic.

2021-01-21 11:22 UTC, crystinutzaa commented
@wp-media/qa please revisit this and approve it if everything seems ok. Thanks!

2021-01-21 17:01 UTC, piotrbak commented
@Tabrisrp @crystinutzaa Check my comments:
1. We should have a possibility to remove the specific host/zone settings
2. We should have a possibility to list the current CDN settings (that will make automation easier)
3. It doesn't include multisite compatibility, we can only enable CDN for the main site
4. Also, when adding another CDN for all assets, shouldn't we delete the first one? Right now it's just adding another below the first. Without the possibility of removal of the host/zone settings, we can have a big mess there

The happy scenarios work correctly.

2021-01-22 13:46 UTC, Tabrisrp commented
Thank you for the feedbacks Piotr.

I'd say, let's go with this MVP version of the command, as a start, and list your additional points as new issues to be worked on later.

I believe it's better to iterate small, especially in this case for a tool that is a side helper.

2021-01-22 14:15 UTC, merged