Fix #22 Activate/Deactivate does not trigger htaccess regeneration
GeekPress/wp-rocket-cli pull request #41
Opened 2020-12-04 10:57 UTC by crystinutzaa

### Identify the issue
Activate / deactivate simply updates the constant `define('WP_CACHE', $value )`
However, during this operation, WP Rocket needs to apply some other mandatory changes like:
1. During Activation when WP_CACHE is set to true
-  Add All WP Rocket rules of the .htaccess file.
-  Delete current cache

2. During deactivation when WP_CACHE is set to false
- Delete All WP Rocket rules of the .htaccess file.
- Clean current cache

### Scope a solution
Rename both functions from `activate` => `activate-cache` and `deactivate` => `deactivate-cache` . This will make clear what is expected from this.
Update functions to do the expected 

### Estimate the effort
Effort `[XS]`

2020-12-07 21:43 UTC, Tabrisrp approved these changes

2021-01-04 12:42 UTC, crystinutzaa commented
@piotrbak this one is ready for testing when you have time 😄

2021-01-11 16:33 UTC, piotrbak commented
@Tabrisrp @crystinutzaa Sorry for all those questions. I have two for this PR too:
- Shouldn't we display a notice to customers when the .htaccess is not writable too? At least during the deactivation?
- What do you think about the fallback for the `activate` and `deactivate` functions? I'm thinking about people who possibly have this command in their scripts.

2021-01-12 21:35 UTC, Tabrisrp commented
- Yes we could add a warning with WP_CLI::warning() if the htaccess is not writable
- We can keep the older command and make them call the new ones, to prevent breaking backward compatibility

2021-01-22 14:25 UTC, Tabrisrp commented
@piotrbak PR updated, you should now have a warning when the htaccess update failed, and the old commands should fallback to the new ones

2021-01-22 18:45 UTC, piotrbak commented
@Tabrisrp there are two identical `clean_wp_rocket_cache` functions in the code at the bottom. Causes fatal error, I'm removing one of them and testing.

2021-01-22 19:07 UTC, piotrbak commented
@Tabrisrp When WP Rocket is deactivated and we run `wp rocket activate-cache`, it throws a fatal error. That's because the WP_CACHE is set to false and we pass the `if statement`.

I'm asking Albert for the Apache environment as all my sites are on NGINX and I can't test the .htaccess part

2021-01-22 19:09 UTC, piotrbak requested changes
Two comments above

2021-01-22 19:19 UTC, Tabrisrp commented
Thank you @piotrbak, those should be fixed now

2021-01-25 16:50 UTC, piotrbak requested changes
@Tabrisrp There are still a couple of things, looks like the last ones:
1. I think during activation/deactivation we should mention that those changes will affect all sites in the multisite network
2. There's a typo here:
https://github.com/wp-media/wp-rocket-cli/blob/e772edfbcd421b240518b23ec66861a21ad29c58/command.php#L79
It should be `deactivate`
3. We should pass `true` there in order to clean the .htaccess:
https://github.com/wp-media/wp-rocket-cli/blob/e772edfbcd421b240518b23ec66861a21ad29c58/command.php#L80
4. `global $is_apache;` is not reliable at all, unfortunately. In my environment, it's `1` when deactivating WP Rocket from the WP Dashboard, **on the other hand, it's `0` during the operations on the WP CLI**. This ends up with errors when trying to change the `.htaccess` content:
https://github.com/wp-media/wp-rocket/blob/df26acdfbe015d056fc442cfbf28734f9635aa9f/inc/functions/htaccess.php#L25

2021-01-25 21:05 UTC, piotrbak commented
@Tabrisrp I tested everything already, the only thing is that we should also check if WP Rocket is activated in the `deactivate-cache` command. This is the only fail here:
[testrail-report-113.pdf](https://github.com/wp-media/wp-rocket-cli/files/5869666/testrail-report-113.pdf)

2021-01-26 15:23 UTC, merged